"""This module is used for storing constant values"""

DATA_DIR = 'data'

TASK_1_FINANCE_COLS = ['Close', 'Open', 'High', 'Adj Close', 'Low', 'Volume']

TASK_2_DATA = {
    'AMD.csv': 'Technology',
    'AAPL.csv': 'Technology',
    'MSFT.csv': 'Technology',
    'NVDA.csv': 'Technology',
    'TSM.csv': 'Technology',
    'ORCL.csv': 'Technology',
    'ASML.csv': 'Technology',
    'INTC.csv': 'Technology',
    'LIN.csv': 'BasicMaterials',
    'BHP.csv': 'BasicMaterials',
    'SHW.csv': 'BasicMaterials',
    'VALE.csv': 'BasicMaterials',
    'SCCO.csv': 'BasicMaterials',
    'ECL.csv': 'BasicMaterials',
    'DOW.csv': 'BasicMaterials',
    'GOOG.csv': 'Communications',
    'META.csv': 'Communications',
    'TMUS.csv': 'Communications',
    'NFLX.csv': 'Communications',
    'DIS.csv': 'Communications',
    'T.csv': 'Communications',
    'ATVI.csv': 'Communications',
    'BIDU.csv': 'Communications',
    'SPOT.csv': 'Communications',
    'AMZN.csv': 'Cyclical',
    'TSLA.csv': 'Cyclical',
    'HD.csv': 'Cyclical',
    'BABA.csv': 'Cyclical',
    'MCD.csv': 'Cyclical',
    'NKE.csv': 'Cyclical',
    'WMT.csv': 'ConsumerDefensive',
    'PG.csv': 'ConsumerDefensive',
    'KO.csv': 'ConsumerDefensive',
    'PM.csv': 'ConsumerDefensive',
    'MNST.csv': 'ConsumerDefensive',
    'KHC.csv': 'ConsumerDefensive',
    'XOM.csv': 'Energy',
    'SHEL.csv': 'Energy',
    'BP.csv': 'Energy',
    'PSX.csv': 'Energy',
    'HES.csv': 'Energy',
    'BRK-B.csv': 'Financial',
    'V.csv': 'Financial',
    'JPM.csv': 'Financial',
    'BML-PG.csv': 'Financial',
    'BX.csv': 'Financial',
    'LLY.csv': 'Healthcare',
    'UNH.csv': 'Healthcare',
    'JNJ.csv': 'Healthcare',
    'AZN.csv': 'Healthcare',
    'NVS.csv': 'Healthcare',
    'PFE.csv': 'Healthcare',
    'SNY.csv': 'Healthcare',
    'CAT.csv': 'Industrial',
    'HON.csv': 'Industrial',
    'GE.csv': 'Industrial',
    'BA.csv': 'Industrial',
    'LMT.csv': 'Industrial',
    'RTX.csv': 'Industrial',
    'FDX.csv': 'Industrial',
    'AMT.csv': 'RealEstate',
    'PSA.csv': 'RealEstate',
    'WELL.csv': 'RealEstate',
    'CCI.csv': 'RealEstate',
    'CSGP.csv': 'RealEstate',
    'VICI.csv': 'RealEstate',
    'SO.csv': 'Utilities',
    'DUK.csv': 'Utilities',
    'SRE.csv': 'Utilities',
    'FTS.csv': 'Utilities'
}